import type { User, Tutor, Booking, Session, Payment, Refund, Dispute, Subject, Admin, Role } from './types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Sarah Chen',
    email: 'sarah.chen@example.com',
    role: 'student',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    createdAt: '2024-01-15',
    lastLogin: '2024-05-03',
  },
  {
    id: 'user-2',
    name: 'James Wilson',
    email: 'james.wilson@example.com',
    role: 'student',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    createdAt: '2024-02-20',
    lastLogin: '2024-05-02',
  },
  {
    id: 'user-3',
    name: 'Maria Garcia',
    email: 'maria.garcia@example.com',
    role: 'tutor',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    createdAt: '2024-01-10',
    lastLogin: '2024-05-04',
  },
  {
    id: 'user-4',
    name: 'Alex Kumar',
    email: 'alex.kumar@example.com',
    role: 'student',
    status: 'blocked',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    createdAt: '2024-03-05',
    lastLogin: '2024-04-20',
  },
];

export const mockTutors: Tutor[] = [
  {
    id: 'tutor-1',
    name: 'Dr. Maria Garcia',
    email: 'maria.garcia@example.com',
    role: 'tutor',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    createdAt: '2024-01-10',
    lastLogin: '2024-05-04',
    bio: 'PhD in Mathematics with 8 years of teaching experience. Specializing in calculus and linear algebra.',
    subjects: ['Mathematics', 'Calculus', 'Linear Algebra'],
    hourlyRate: 50,
    experience: 8,
    rating: 4.9,
    totalSessions: 156,
    certificates: [
      { id: 'cert-1', name: 'PhD Mathematics', issuer: 'Stanford University', url: '#', uploadedAt: '2024-01-10' },
    ],
    approvalStatus: 'approved',
    submittedAt: '2024-01-10',
    approvedAt: '2024-01-15',
  },
  {
    id: 'tutor-2',
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'tutor',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    createdAt: '2024-02-01',
    lastLogin: '2024-05-03',
    bio: 'IELTS instructor with 6 years of experience. Helped 500+ students achieve their target bands.',
    subjects: ['English', 'IELTS', 'TOEFL'],
    hourlyRate: 35,
    experience: 6,
    rating: 4.8,
    totalSessions: 203,
    certificates: [
      { id: 'cert-2', name: 'IELTS Instructor Certification', issuer: 'British Council', url: '#', uploadedAt: '2024-02-01' },
    ],
    approvalStatus: 'approved',
    submittedAt: '2024-02-01',
    approvedAt: '2024-02-10',
  },
  {
    id: 'tutor-3',
    name: 'Emily Chen',
    email: 'emily.chen@example.com',
    role: 'tutor',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    createdAt: '2024-03-15',
    bio: 'MBA graduate specializing in interview preparation and career counseling for business school candidates.',
    subjects: ['MBA', 'Business', 'Interview Prep'],
    hourlyRate: 60,
    experience: 4,
    rating: 4.7,
    totalSessions: 89,
    certificates: [
      { id: 'cert-3', name: 'MBA Harvard', issuer: 'Harvard Business School', url: '#', uploadedAt: '2024-03-15' },
    ],
    approvalStatus: 'pending',
    submittedAt: '2024-04-20',
  },
  {
    id: 'tutor-4',
    name: 'Rajesh Patel',
    email: 'rajesh.patel@example.com',
    role: 'tutor',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh',
    createdAt: '2024-04-01',
    bio: 'GRE and GMAT expert with 95+ percentile background. Proven track record of student success.',
    subjects: ['GRE', 'GMAT', 'Quantitative Reasoning'],
    hourlyRate: 55,
    experience: 5,
    rating: 4.6,
    totalSessions: 127,
    certificates: [
      { id: 'cert-4', name: 'GRE/GMAT Instructor Certification', issuer: 'Test Prep Institute', url: '#', uploadedAt: '2024-04-01' },
    ],
    approvalStatus: 'pending',
    submittedAt: '2024-04-28',
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'booking-1',
    studentId: 'user-1',
    tutorId: 'tutor-1',
    subject: 'Mathematics',
    startTime: '2024-05-10T14:00:00',
    endTime: '2024-05-10T15:00:00',
    status: 'confirmed',
    paymentStatus: 'succeeded',
    amount: 50,
    createdAt: '2024-05-05',
  },
  {
    id: 'booking-2',
    studentId: 'user-2',
    tutorId: 'tutor-2',
    subject: 'English',
    startTime: '2024-05-12T10:00:00',
    endTime: '2024-05-12T11:00:00',
    status: 'pending',
    paymentStatus: 'pending',
    amount: 35,
    createdAt: '2024-05-04',
  },
  {
    id: 'booking-3',
    studentId: 'user-1',
    tutorId: 'tutor-2',
    subject: 'IELTS',
    startTime: '2024-05-15T16:00:00',
    endTime: '2024-05-15T17:00:00',
    status: 'confirmed',
    paymentStatus: 'succeeded',
    amount: 35,
    createdAt: '2024-05-02',
  },
];

export const mockSessions: Session[] = [
  {
    id: 'session-1',
    bookingId: 'booking-1',
    studentId: 'user-1',
    tutorId: 'tutor-1',
    subject: 'Mathematics',
    startTime: '2024-05-10T14:00:00',
    endTime: '2024-05-10T15:00:00',
    status: 'completed',
    joinLink: 'https://zoom.us/j/123456789',
    recordingUrl: 'https://example.com/recording-1',
    feedback: 'Great session! Maria explained the concepts clearly.',
    createdAt: '2024-05-10',
  },
];

export const mockPayments: Payment[] = [
  {
    id: 'payment-1',
    bookingId: 'booking-1',
    amount: 50,
    currency: 'USD',
    status: 'succeeded',
    method: 'card',
    studentId: 'user-1',
    tutorId: 'tutor-1',
    createdAt: '2024-05-05',
    paidAt: '2024-05-05',
    transactionId: 'txn_1234567890',
  },
  {
    id: 'payment-2',
    bookingId: 'booking-2',
    amount: 35,
    currency: 'USD',
    status: 'pending',
    method: 'card',
    studentId: 'user-2',
    tutorId: 'tutor-2',
    createdAt: '2024-05-04',
  },
];

export const mockRefunds: Refund[] = [
  {
    id: 'refund-1',
    paymentId: 'payment-1',
    amount: 25,
    status: 'approved',
    reason: 'session_cancelled',
    studentId: 'user-1',
    requestedAt: '2024-04-30',
    processedAt: '2024-05-02',
    note: 'Partial refund due to session rescheduling.',
  },
];

export const mockDisputes: Dispute[] = [
  {
    id: 'dispute-1',
    studentId: 'user-2',
    tutorId: 'tutor-1',
    bookingId: 'booking-2',
    status: 'open',
    priority: 'high',
    subject: 'Session Quality Issue',
    description: 'The tutor did not show up on time for the scheduled session.',
    createdAt: '2024-05-01',
  },
  {
    id: 'dispute-2',
    studentId: 'user-1',
    tutorId: 'tutor-2',
    bookingId: 'booking-3',
    status: 'under_review',
    priority: 'medium',
    subject: 'Unclear Instructions',
    description: 'The lesson material was not as advertised.',
    createdAt: '2024-04-28',
  },
];

export const mockSubjects: Subject[] = [
  { id: 'subject-1', name: 'Mathematics', slug: 'mathematics', description: 'All levels of mathematics', status: 'active', createdAt: '2024-01-01' },
  { id: 'subject-2', name: 'English', slug: 'english', description: 'English language and literature', status: 'active', createdAt: '2024-01-01' },
  { id: 'subject-3', name: 'IELTS', slug: 'ielts', description: 'IELTS exam preparation', status: 'active', createdAt: '2024-01-01' },
  { id: 'subject-4', name: 'GMAT', slug: 'gmat', description: 'GMAT exam preparation', status: 'active', createdAt: '2024-01-01' },
  { id: 'subject-5', name: 'GRE', slug: 'gre', description: 'GRE exam preparation', status: 'active', createdAt: '2024-01-01' },
];

export const mockAdmins: Admin[] = [
  { id: 'admin-1', name: 'Super Admin', email: 'admin@connecti.com', role: 'super_admin', status: 'active', createdAt: '2024-01-01' },
  { id: 'admin-2', name: 'Operations Lead', email: 'ops@connecti.com', role: 'operations_admin', status: 'active', createdAt: '2024-02-01' },
  { id: 'admin-3', name: 'Finance Manager', email: 'finance@connecti.com', role: 'finance_admin', status: 'active', createdAt: '2024-02-15' },
];

export const mockRoles: Role[] = [
  {
    id: 'role-1',
    name: 'super_admin',
    permissions: {
      users: ['create', 'read', 'update', 'delete'],
      tutors: ['create', 'read', 'update', 'delete', 'approve', 'reject'],
      bookings: ['create', 'read', 'update', 'delete'],
      sessions: ['create', 'read', 'update', 'delete'],
      payments: ['create', 'read', 'update', 'delete'],
      refunds: ['create', 'read', 'update', 'delete', 'approve', 'reject'],
      disputes: ['create', 'read', 'update', 'delete', 'approve', 'reject'],
      subjects: ['create', 'read', 'update', 'delete'],
      admins: ['create', 'read', 'update', 'delete'],
    },
  },
  {
    id: 'role-2',
    name: 'operations_admin',
    permissions: {
      users: ['read', 'update'],
      tutors: ['read', 'approve', 'reject'],
      bookings: ['read', 'update'],
      sessions: ['read'],
      payments: ['read'],
      refunds: ['read', 'approve', 'reject'],
      disputes: ['read', 'update'],
      subjects: ['read', 'create', 'update'],
      admins: ['read'],
    },
  },
  {
    id: 'role-3',
    name: 'finance_admin',
    permissions: {
      users: ['read'],
      tutors: ['read'],
      bookings: ['read'],
      sessions: ['read'],
      payments: ['read', 'update'],
      refunds: ['read', 'update', 'approve', 'reject'],
      disputes: ['read'],
      subjects: ['read'],
      admins: ['read'],
    },
  },
];
