import { Session } from './types';

export const MOCK_SESSIONS: Session[] = [
  {
    id: 'sess-001',
    bookingId: 'book-101',
    studentId: 'stud-001',
    tutor: {
      id: 'tutor-001',
      fullName: 'Dr. Sarah Wilson',
      avatarUrl: 'https://i.pravatar.cc/150?u=sarah',
    },
    subject: 'Advanced Physics',
    startTime: '2024-05-20T14:00:00Z',
    endTime: '2024-05-20T15:00:00Z',
    meetingProvider: 'zoom',
    meetingUrl: 'https://zoom.us/j/123456789',
    status: 'scheduled',
    paymentSummary: {
      amount: 60,
      status: 'paid',
      transactionId: 'txn_001',
    },
    feedbackStatus: 'pending',
  },
  {
    id: 'sess-002',
    bookingId: 'book-102',
    studentId: 'stud-001',
    tutor: {
      id: 'tutor-002',
      fullName: 'James Miller',
      avatarUrl: 'https://i.pravatar.cc/150?u=james',
    },
    subject: 'Calculus II',
    startTime: '2024-05-10T10:00:00Z',
    endTime: '2024-05-10T11:00:00Z',
    meetingProvider: 'google_meet',
    meetingUrl: 'https://meet.google.com/abc-defg-hij',
    status: 'completed',
    paymentSummary: {
      amount: 45,
      status: 'paid',
      transactionId: 'txn_002',
    },
    feedbackStatus: 'submitted',
  },
  {
    id: 'sess-003',
    bookingId: 'book-103',
    studentId: 'stud-001',
    tutor: {
      id: 'tutor-003',
      fullName: 'Robert Fox',
      avatarUrl: 'https://i.pravatar.cc/150?u=robert',
    },
    subject: 'Biology',
    startTime: '2024-05-05T16:00:00Z',
    endTime: '2024-05-05T17:00:00Z',
    meetingProvider: 'zoom',
    status: 'cancelled',
    cancelReason: 'Tutor emergency',
    paymentSummary: {
      amount: 50,
      status: 'refunded',
      transactionId: 'txn_003',
    },
    feedbackStatus: 'not_applicable',
  },
  {
    id: 'sess-004',
    bookingId: 'book-104',
    studentId: 'stud-001',
    tutor: {
      id: 'tutor-001',
      fullName: 'Dr. Sarah Wilson',
      avatarUrl: 'https://i.pravatar.cc/150?u=sarah',
    },
    subject: 'Physics Essentials',
    startTime: '2024-05-25T09:00:00Z',
    endTime: '2024-05-25T10:00:00Z',
    meetingProvider: 'zoom',
    status: 'scheduled',
    paymentSummary: {
      amount: 60,
      status: 'paid',
      transactionId: 'txn_004',
    },
    feedbackStatus: 'pending',
  },
];
