import { AuthUser } from './types';

export const MOCK_USERS: (AuthUser & { password?: string })[] = [
  {
    id: 'user_student_1',
    email: 'student@example.com',
    password: 'password123',
    fullName: 'Alex Student',
    role: 'student',
    status: 'active',
    onboardingCompleted: true,
  },
  {
    id: 'user_tutor_1',
    email: 'tutor@example.com',
    password: 'password123',
    fullName: 'Dr. Sarah Wilson',
    role: 'tutor',
    status: 'active',
    approvalStatus: 'approved',
    onboardingCompleted: true,
  },
  {
    id: 'user_tutor_pending',
    email: 'pending@example.com',
    password: 'password123',
    fullName: 'Peter Pending',
    role: 'tutor',
    status: 'active',
    approvalStatus: 'pending',
    onboardingCompleted: true,
  },
  {
    id: 'user_tutor_rejected',
    email: 'rejected@example.com',
    password: 'password123',
    fullName: 'Randy Rejected',
    role: 'tutor',
    status: 'active',
    approvalStatus: 'rejected',
    onboardingCompleted: true,
  },
  {
    id: 'user_student_blocked',
    email: 'blocked@example.com',
    password: 'password123',
    fullName: 'Ben Blocked',
    role: 'student',
    status: 'blocked',
    onboardingCompleted: true,
  },
  {
    id: 'user_new_student',
    email: 'newbie@example.com',
    password: 'password123',
    fullName: 'New Student',
    role: 'student',
    status: 'active',
    onboardingCompleted: false,
  }
];
